### PR TITLE
Update 7zip url for latest version

### LINKED ISSUE #266: Installation breaks when trying to download or load 7z920.msi
## Issue Description
Running Virtualbox under Ubuntu 17.10 64 bits. Trying to build metasploitable 3 running the command ./build.sh windows2008. Procedure halts with an error (see sommand output). My best guess (and suggestion from the IRC) is that the script failed in downloading 7z920-x64.msi from Sourceforge due to a time out of some kind. Manual download works fine, though it does take a while for the page to load.

## Host System
* OS: Ubuntu 17.10 64 bits
* Packer Version: 1.2.2
* Vagrant Version: 2.0.3
* VirtualBox Version: 5.2.8 r121009 (Qt5.9.1)

## Command Output
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\thawte_primary_root.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "Root" A:\utn-userfirst.cer
    virtualbox-iso: Root
    virtualbox-iso: Signature matches Public Key
    virtualbox-iso: Certificate "CN=UTN-USERFirst-Object, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, S=UT, C=US" added to store.
    virtualbox-iso: CertUtil: -addstore command completed successfully.
    ==> virtualbox-iso: Provisioning with shell script: /home/jurgen/git/metasploitable3/packer/templates/../../scripts/installs/vm-guest-tools.bat
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if not exist "C:\Windows\Temp\7z920-x64.msi" (powershell -Command "(New-Object System.Net.WebClient).DownloadFile('http://www.7-zip.org/a/7z920-x64.msi', 'C:\Windows\Temp\7z920-x64.msi')"  0<NUL )
    virtualbox-iso: Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to th
    virtualbox-iso: e remote server"
    virtualbox-iso: At line:1 char:47
    virtualbox-iso: + (New-Object System.Net.WebClient).DownloadFile <<<< ('http://www.7-zip.org/a/
    virtualbox-iso: 7z920-x64.msi', 'C:\Windows\Temp\7z920-x64.msi')
    virtualbox-iso:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    virtualbox-iso:     + FullyQualifiedErrorId : DotNetMethodException
    virtualbox-iso:
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>msiexec /qb /i C:\Windows\Temp\7z920-x64.msi
    virtualbox-iso: This installation package could not be opened.  Verify that the package exists and that             you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.
    virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso: 
    virtualbox-iso: C:\Users\vagrant>if "virtualbox-iso" EQU "vmware-iso" goto :vmware
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>if "virtualbox-iso" EQU "virtualbox-iso" goto :virtualbox
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>move /Y C:\Users\vagrant\VBoxGuestAdditions.iso C:\Windows\Temp
    virtualbox-iso:         1 file(s) moved.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c ""C:\Program Files\7-Zip\7z.exe" x C:\Windows\Temp\VBoxGuestAdditions.iso -oC:\Windows\Temp\virtualbox"
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c certutil -addstore -f "TrustedPublisher" C:\Windows\Temp\virtualbox\cert\vbox-sha1.cer
    virtualbox-iso: TrustedPublisher
    virtualbox-iso: DecodeFile returned The system cannot find the path specified. 0x80070003 (WIN32: 3)
    virtualbox-iso: CertUtil: -addstore command FAILED: 0x80070003 (WIN32: 3)
    virtualbox-iso: CertUtil: The system cannot find the path specified.
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>cmd /c C:\Windows\Temp\virtualbox\VBoxWindowsAdditions.exe /S
    virtualbox-iso:
    virtualbox-iso: The system cannot find the path specified.
    virtualbox-iso: C:\Users\vagrant>goto :done
    virtualbox-iso:
    virtualbox-iso: C:\Users\vagrant>msiexec /qb /x C:\Windows\Temp\7z920-x64.msi
    virtualbox-iso: This installation package could not be opened.  Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.
    virtualbox-iso: 
    ==> virtualbox-iso: Deregistering and deleting VM...
    ==> virtualbox-iso: Deleting output directory...
    Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 83

    ==> Some builds didn't complete successfully and had errors:
    --> virtualbox-iso: Script exited with non-zero exit status: 83

## Suggestion for improvement of the script
Maybe the script could check in some local folder if a given file can be found - prior to downloading or after a  failure. This would allow us users to circumvent sites from preventing scripted downloads.

### PR DESCRIPTION
**Pull request by jmartin-r7**
Fix #266 due to previous version now behind soureforge redirect.

### CODE REVIEW

**Comment by JurgenG** [comment]
Maybe it would be better to link to some long term supported version of 7Z, for example the one that is posted just underneath the beta version... dating back to 2016. It looks like that is the final release of a previous version. When looking on Sourceforge, the current beta is there being spread as the latest stable, so I assume the current version will be changing soon.

If explicitly needing the latest version, there will have to be some regex magic to extract the filename from the HTML source code of the download page (the first a href url inside a table element) will point to the latest version.

**Comment by jmartin-r7** [comment]
@JurgenG those are possible options, and happy to consider PRs for the approaches.  At this time the sourceforge redirect causes complexity that will take time to address in a way compatible with powershell. This PR gets the project working now and can be enhanced in the future.

**Comment by JurgenG** [comment]
This link doesn't redirect to Sourceforge: https://www.7-zip.org/a/7z1604-x64.exe
(it is the latest release of the previous version). I'm assuming it contains enough features for what is needed in metasploitable.

**Comment by jmartin-r7** [comment]
Thanks for the quick update. This sounds good and may extend the update for a bit longer given the current beta for 18.x.

Also shifted file names a bit so if there is a next time it will be a one-line update.

**Pull request merged**
