### PR TITLE
Add Flags

### PR DESCRIPTION
**Pull request by wchen-r7**
add flags for Metasploitable3

### CODE REVIEW

**Comment by jbarnett-r7** [comment]
I'm hitting a few access denied errors when attempting to install the flags. I think maybe some of the commands need to be run before removing permissions from the other user groups?

```
==> default: C:\Windows\system32>cacls "C:\WINDOWS\System32\jack_of_clubs.png" /t /e /g SYSTEM:f 
==> default: processed file: C:\WINDOWS\System32\jack_of_clubs.png
==> default: 
==> default: Access is denied.
==> default: 
==> default: 
==> default: C:\Windows\system32>cacls "C:\WINDOWS\System32\jack_of_clubs.png" /R Administrators /E 
==> default: processed file: C:\WINDOWS\System32\jack_of_clubs.png
==> default: 
==> default: C:\Windows\system32>cacls "C:\WINDOWS\System32\jack_of_clubs.png" /R Users /E 
==> default: processed file: C:\WINDOWS\System32\jack_of_clubs.png
==> default: 
==> default: C:\Windows\system32>attrib +h "C:\WINDOWS\System32\jack_of_clubs.png" 
==> default: Access denied - C:\WINDOWS\System32\jack_of_clubs.png
==> default: 
==> default: 
==> default: C:\Windows\system32>copy C:\vagrant\resources\flags\three_of_spades.png C:\Windows 
==> default:         1 file(s) copied.
==> default: 
==> default: C:\Windows\system32>cacls "C:\Windows\three_of_spades.png" /t /e /g SYSTEM:f 
==> default: processed file: C:\Windows\three_of_spades.png
==> default: 
==> default: Access is denied.
==> default: 
==> default: 
==> default: C:\Windows\system32>cacls "C:\Windows\three_of_spades.png" /R Administrators /E 
==> default: processed file: C:\Windows\three_of_spades.png
==> default: 
==> default: C:\Windows\system32>cacls "C:\Windows\three_of_spades.png" /R USERS /E 
==> default: processed file: C:\Windows\three_of_spades.png
==> default: 
==> default: C:\Windows\system32>attrib +h "C:\Windows\three_of_spades.png" 
==> default: Access denied - C:\Windows\three_of_spades.png
```

**Comment by wchen-r7** [comment]
I've rearranged the permissions.

**Comment by jbarnett-r7** [comment]
Ok cool. I'll rebuild. Everything else was good so once that checks out I'll land it.

**Comment by wchen-r7** [comment]
Hey @jbarnett-r7 Sorry for the last min flag, but I also just added another one - Ace of Hearts for Egyp7. You will have to pull and rebuild again. Sorry for the trouble. Thanks!

**Comment by jbarnett-r7** [comment]
Looks good with the latest fixes and new flag. Going to merge.

**Pull request merged**
