### PR TITLE
Updated powershell script

### PR DESCRIPTION
**Pull request by Chan9390**
Deleted the old `build_win2008.ps1` script and added new powershell script (`build.ps1`). The new script allows the user to build both the boxes. Also updated vagrant and powershell build commands in the readme file.

### Steps to test

- [ ] `.\build.ps1 windows2008` - builds windows box
- [ ] `.\build.ps1 ubuntu1404` - builds linux box
- [ ] `.\build.ps1` - builds both boxes after a confirmation from user
- [ ] `.\build.ps1 something` - should return the message `Invalid OS. Valid options are 'ubuntu1404' and 'windows2008'`

**Version of software used**
- Windows 10 Home
- Vagrant : 2.0.3
- Packer : 1.2.2
- VirtualBox : 5.2.8

### CODE REVIEW

**Comment by Chan9390** [comment]
Closes #271, #272

**Comment by Chan9390** [comment]
Closes #248

**Comment by designofhumanity** [comment]
default

What should be in Vagrant file (Dowload Vagrant file from this branch)? Where should be box file?

**Comment by designofhumanity** [comment]
vagrant up not working, but vagrant up win2k8 working (in background)
default

**Comment by jmartin-r7** [comment]
This works as is, there may still need to be some cleanup that can be completed iteratively.

Thanks @Chan9390

**Comment by Chan9390** [comment]
Thanks for merging @jmartin-r7

**Pull request merged**
