### PR TITLE
Add initial support for building and using libvirt boxes when available

### PR DESCRIPTION
**Pull request by devec0**
Allows the building of libvirt boxes for those without VirtualBox, who maybe do not want to run VirtualBox due to the proprietary drivers under Linux.

Also adds required virtio signed drivers to Windows image to allow smooth sailing under the KVM hypervisor.

Will default to Virtualbox if installed to avoid breaking backwards compatibility.

### CODE REVIEW

**Comment by idrissbellil** [comment]
What about ubuntu ?

**Comment by devec0** [comment]
Given this was tested on Ubuntu, can you elaborate on what you are asking?

**Comment by devec0** [comment]
Ah, OK - I think you're referring to the Ubuntu box.
I wasn't familiar with it, as the Ubuntu box was added a considerable time after I initially proposed these changes. The MP will need additional changes to add a libvirt target for the ubuntu1404 box.

**Comment by idrissbellil** [comment]
exactly, I thought it will be nice to get both of them working on boxes rather than Virtualbox, thanks for the wonderful contribution (Windows box)

**Comment by devec0** [comment]
Changes for Ubuntu 14.04 box are on their way! Just doing a test build now after getting my head around the reshuffle (which is an excellent idea, btw)

**Comment by devec0** [comment]
OK, rebased from current master and added support for a libvirt/qemu build of the ubuntu1404 box too. The templates have also been updated for both Windows and Ubuntu to use the new paths and variables used for the other builders (vbox + vmware)

**Comment by jmartin-r7** [comment]
@devec0, thank you for your contribution and doing the leg work get this setup.  

I have some concern about including the files you have added in `resources/drivers/virtio`. These files look like they "may" fall under a BSD license [virtio-win/kvm-guest-drivers-windows](https://github.com/virtio-win/kvm-guest-drivers-windows) however I see some conflicting GPLv2 distributions as well at [Fedora](https://docs.fedoraproject.org/quick-docs/en-US/creating-windows-virtual-machines-using-virtio-drivers.html).  While open source I would like to see these drivers obtained from original trusted distribution sources during the build vs distributed as binary files in the this repository.

If you look closely at how tools and utilities needed in the current builds are preformed, my request would bring this contribution more inline with the standard here. 

You mention specifically in your PR the idea that some may baulk an using *proprietary* drivers for virutalbox, I feel you can appreciate the concern about using repository "provided" binaries.

**Pull request closed without merging**
