### PR TITLE
Hyper-V support.

### PR DESCRIPTION
**Pull request by GabrielTK**
Hey guys,
Just adding Hyper-V support. Can anyone test it please??
Thank you,
Gabriel

### CODE REVIEW

**Comment by GabrielTK** [comment]
I know the SSH setup has been uploaded with the code, but this makes hyper-v building possible and speeds up the build process on other Virtualization Solutions, as the download isn't needed.

**Comment by GabrielTK** [comment]
I know the SSH setup has been uploaded with the code, but this makes hyper-v building possible and speeds up the build process on other Virtualization Solutions, as the download isn't needed.

**Comment by jbarnett-r7** [comment]
Hey @GabrielTK Thanks for this PR. I don't have a HyperV instance readily available to test this with, but I'll try to get one set up. Excited to test it out.

**Comment by khuongduybui** [comment]
I don't know what you tried to do with https://github.com/GabrielTK/metasploitable3/commit/8dfd08f93a5be310ce9ee2b96b7f301b3e001626 but I still got the corrupted file issue. You are putting more than 1.4MB into a "Floppy Drive" image and Windows Server 2008 cut off the file. 👎

**Comment by GabrielTK** [comment]
Makes Sense... Will see what can be done. Thanks for pointing that out, I didn't actually remember Floppy Disk limits.

**Comment by josharmentrout1** [comment]
Getting hung up on "Waiting for SSH to become available..."  
Build 'hyperv-iso' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> hyperv-iso: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.

**Comment by bwatters-r7** [comment]
@josharmentrout1 that's (unfortunately) a really common error.  In the past, the most common reason I get that error is when I screw up the networking and my build machine can talk to the hypervisor, but not the the VM.  Sadly, there are a bunch of reasons that error might pop up, from errant network connections to a catastrophic VM creation failure.  If it were me, I'd run through this troubleshooting process: 
Is the VM created?
Can you power it on?
Does the VM have an IP address?
Is port 22 listening/ssh service running?
Can you ping it?
Can you netcat port 22 from your build machine?

**Comment by busterb** [comment]
Let's focus on #332 for this feature

**Pull request closed without merging**
