### PR TITLE
Add the Linux Box From the 2017 CTF

### PR DESCRIPTION
**Pull request by jbarnett-r7**
This PR adds in the code for the Linux box that was used for the [capture the flag competition](https://blog.rapid7.com/2017/12/11/congrats-to-the-winners-of-our-2017-community-ctf/) from December 2017.

Since there is now 2 boxes within the project, the build script was updated to support building multiple boxes. When using the bash build script, you will now need to pass in the OS that you want to build, e.g. `./build.sh win2008`. This will build the box using Packer and import it into Vagrant.

NOTE: The Powershell build script has not been updated to support building the Linux box yet (because I'm not very good at Powershell). It will need to be built manually on Windows. If anyone wants to update the Powershell script to support building the new box that would be much appreciated.

Verification:
- [ ] Build the Linux box using `./build.sh ub1404`
- [ ] Bring up the Linux box using `vagrant up ub1404`
- [ ] Verify you can login to the box using U: `vagrant` P: `vagrant` and that various services are running correctly.

### CODE REVIEW

**Comment by mubix** [comment]
You all are amazing. Thank you so much for all the work on this!

**Comment by busterb** [comment]
Thanks @jbarnett-r7 and @wchen-r7 , epic work guys!

**Comment by g0tmi1k** [comment]
Permission to add this to VulnHub (https://www.vulnhub.com/) ?

**Comment by captainkyd** [comment]
Nicely done, been stoked for the Linux box for 3 since y’all first said it was coming.

**Pull request merged**
