### PR TITLE
just info updated Update README.md

### PR DESCRIPTION
**Pull request by shawnfrost69**

### CODE REVIEW

**Comment by deargle** [comment]
A link to hacktoberfest?

**Comment by deargle** [comment]
Ah I see, [the entirety of github is being spammed with hacktoberfest garbage PRs](https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama)

@jmartin-r7 I promise that none of the six I opened today are spam 😄

**Comment by adfoster-r7** [comment]
Marking as `spam` as suggested by the [hacktoberfest faq](https://hacktoberfest.digitalocean.com/faq):

> If a repository maintainer decides a pull request you made was spammy or an unhelpful contribution to the project, they can add an invalid or spam label to your PR. This lets us know they do not think your pull request is a quality contribution, so it will not count toward Hacktoberfest.

**Comment by adfoster-r7** [comment]
Thanks for the heads up @deargle :+1:

**Pull request closed without merging**
